/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartAnalysisPopupRouteImport } from './routes/smart-analysis-popup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PageRouteImport } from './routes/page'
import { Route as MentorChatRouteImport } from './routes/mentor-chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SmartAnalysisPopupRoute = SmartAnalysisPopupRouteImport.update({
  id: '/smart-analysis-popup',
  path: '/smart-analysis-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorChatRoute = MentorChatRouteImport.update({
  id: '/mentor-chat',
  path: '/mentor-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mentor-chat': typeof MentorChatRoute
  '/page': typeof PageRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/paywall': typeof PaywallRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/smart-analysis-popup': typeof SmartAnalysisPopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mentor-chat': typeof MentorChatRoute
  '/page': typeof PageRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/paywall': typeof PaywallRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/smart-analysis-popup': typeof SmartAnalysisPopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mentor-chat': typeof MentorChatRoute
  '/page': typeof PageRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/paywall': typeof PaywallRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/smart-analysis-popup': typeof SmartAnalysisPopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/mentor-chat'
    | '/page'
    | '/payment-success'
    | '/paywall'
    | '/plan'
    | '/pricing'
    | '/smart-analysis-popup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/mentor-chat'
    | '/page'
    | '/payment-success'
    | '/paywall'
    | '/plan'
    | '/pricing'
    | '/smart-analysis-popup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/mentor-chat'
    | '/page'
    | '/payment-success'
    | '/paywall'
    | '/plan'
    | '/pricing'
    | '/smart-analysis-popup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MentorChatRoute: typeof MentorChatRoute
  PageRoute: typeof PageRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PaywallRoute: typeof PaywallRoute
  PlanRoute: typeof PlanRoute
  PricingRoute: typeof PricingRoute
  SmartAnalysisPopupRoute: typeof SmartAnalysisPopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-analysis-popup': {
      id: '/smart-analysis-popup'
      path: '/smart-analysis-popup'
      fullPath: '/smart-analysis-popup'
      preLoaderRoute: typeof SmartAnalysisPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-chat': {
      id: '/mentor-chat'
      path: '/mentor-chat'
      fullPath: '/mentor-chat'
      preLoaderRoute: typeof MentorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MentorChatRoute: MentorChatRoute,
  PageRoute: PageRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PaywallRoute: PaywallRoute,
  PlanRoute: PlanRoute,
  PricingRoute: PricingRoute,
  SmartAnalysisPopupRoute: SmartAnalysisPopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
